server:
  port: 80

spring:
  application:
    name: cloud-feign-server
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
# open feign 默认支持ribbon 超时控制交给ribbon 设置feign客户端超时时间
ribbon:
  # 建立链接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  # 建立链接所用的时间，用户网络正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.zjt.cloud.rpcserve: debug