server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 127.0.0.1
      port: 8600
      discovery:
        service-name: ${spring.application.name}
        #hostname: 127.0.0.1