server:
  port: 2003

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_account?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: myuser
  application:
    name: seata-account-service
  main:
    allow-bean-definition-overriding: true
  cloud:
#    alibaba:
#      seata:
#        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
        group: SEATA_GROUP
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
    enable-degrade: false
    disable-global-transaction: false
  config:
    type: nacos
    nacos:
      group: "SEATA_GROUP"
      server-addr: localhost:8848
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      group: "SEATA_GROUP"
      server-addr: localhost:8848
      username: "nacos"
      password: "nacos"
      application: seata-server
  enable-auto-data-source-proxy: true


##seata配置
#seata:
#  enabled: true
#  application-id: 你的当前服务的application name
#  #这里的名字与file.conf中vgroup_mapping.my_test_tx_group = "default"相同
#  tx-service-group: my_test_tx_group
#  enable-auto-data-source-proxy: true
#  #  use-jdk-proxy: false
#  service:
#    #这里的名字与file.conf中vgroup_mapping.my_test_tx_group = "default"相同
#    vgroup-mapping:
#      my_test_tx_group: default
#      #这里的名字与file.conf中default.grouplist = "127.0.0.1:8091"相同
#    grouplist:
#      default: 127.0.0.1:8091
#  #      disable-global-transaction: false
#  config:
#    type: nacos
#    nacos:
#      namespace:
#      #这里的地址就是你的nacos的地址,可以更换为线上
#      serverAddr: 127.0.0.1:8848
#      #这里的名字就是registry.conf中 nacos的group名字
#      group: SEATA_GROUP
#      userName: "nacos"
#      password: "nacos"
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      #这里的地址就是你的nacos的地址,可以更换为线上
#      server-addr: 127.0.0.1:8848
#      #这里的名字就是registry.conf中 nacos的group名字
#      group: SEATA_GROUP
#      namespace:
#      userName: "nacos"
#      password: "nacos"
