server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:10086 # 配置nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
