server:
  port: 8006

spring:
  application:
    name: consul-provider-payment # 微服务名称 注册进入是临时节点
  cloud:
    consul:
      host: 127.0.0.1
      port: 8600
      discovery:
        service-name: ${spring.application.name}