server:
  port: 8001


spring:
  application:
    name: cloud-payment-service # 微服务名称
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql 驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db2020?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: myuser
  #flyway 不指定默认排序
  flyway:
    out-of-order: true
  # 先关闭热部署，老是重启电脑卡有点烦
  devtools:
    add-properties: false
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  # 所有Entity类所在的包
  type-aliases-package: com.zjt.cloud.domain
  #configuration:
  # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.zjt.cloud.dao: debug
    org:
      apache:
        ibatis: info
# eureka 相关配置文件
eureka:
  client:
    # 表示将自己注册进入 Eureka Server 默认为true
    register-with-eureka: true
    # 是否从 Eureka Server 抓取已有的注册信息，默认为true，集群时必须设置为true 才能配合 ribbon 使用 负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true # 访问路径可以显示IP
    # eureka 客户端 服务端发送心跳的时间间隔，单位秒 默认 30s
    lease-renewal-interval-in-seconds: 1
    # eureka 服务端在收到最后一次心跳后等待时间上限，单位是秒默认是90s 超时将会清除微服务
    lease-expiration-duration-in-seconds: 2