server:
  port: 83

spring:
  application:
    name: nacos-payment-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置nacos地址
# open feign 默认支持ribbon 超时控制交给ribbon 设置feign客户端超时时间
ribbon:
  # 建立链接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  # 建立链接所用的时间，用户网络正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.zjt.cloud.rpcserve: debug